name: Publish Docker Image

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: echo "${{secrets.DOCKER_HUB_TOKEN}}" | docker login -u "${{secrets.DOCKER_HUB_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag "${{secrets.DOCKER_HUB_USERNAME}}"/ums-auth-asw-cicd:latest

      - name: Push Docker Image to docker hub
        run: docker push "${{secrets.DOCKER_HUB_USERNAME}}"/ums-auth-asw-cicd:latest
